export const TORBOX_API_BASE = 'https://api.torbox.app'
export const SIMKL_API_BASE = 'https://api.simkl.com'
export const NUVIO_API_BASE = 'https://api.nuvio.tv'
export const SIMKL_AUTH_BASE = 'https://simkl.com'
export const TRAKT_API_BASE = 'https://api.trakt.tv'
export const TRAKT_AUTH_BASE = 'https://trakt.tv'
